rd/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

router = DefaultRouter()
router.register(r'spareparts', views.SparePartViewSet)

# app_name = 'polls'
# urlpatterns = [
#     path("", views.IndexView.as_view(), name="index"),
# ]
app_name = 'rd'
urlpatterns = [
    # path("", views.index, name="index"),
    path("", views.PartsView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/edit/", views.PartUpdateView.as_view(), name="part_edit"),
    path("<int:pk>/delete/", views.PartDeleteView.as_view(), name="part_delete"),
    path("create/", views.create_view, name="part_create"),
    path("api/", include(router.urls)),
]

rd_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rd/', include('rd.urls')),
]

rd/models.py
from django.db import models

# Create your models here.

class Location(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Owner(models.Model):
    name = models.CharField(max_length=20)
    surname = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.name} {self.surname}"
    
class SparePart(models.Model):
    name = models.CharField("naziv", max_length=50)
    type = models.CharField("tip", max_length=20)
    dop = models.DateField("datum nabave")
    owner = models.ForeignKey(Owner, on_delete=models.CASCADE, verbose_name="lastnik")
    location = models.ForeignKey(Location, on_delete=models.CASCADE, verbose_name="lokacija")

    def __str__(self):
        return f"{self.name} - {self.type}"
    
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('rd:detail', args=[str(self.id)])

rd/forms.py
from django import forms
from .models import SparePart

class SparePartForm(forms.ModelForm):
    class Meta:
        model = SparePart
        fields = ['name', 'type', 'dop', 'owner', 'location']

rd/views.py
from django.shortcuts import redirect, render

# Create your views here.
from django.http import HttpResponse
from django.views import generic
from django_tables2 import SingleTableView

from .models import Location, Owner, SparePart
from .tables import PartsTable
from .forms import SparePartForm

class PartsView(SingleTableView):
    model = SparePart
    table_class = PartsTable
    paginate_by = 15
    template_name = 'rd/index.html'

def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

class DetailView(generic.DetailView):
    model = SparePart
    template_name = 'rd/part_detail.html'

# update
class PartUpdateView(generic.UpdateView):
    model = SparePart
    fields = ['name', 'type', 'dop', 'owner', 'location']
    template_name = 'rd/part_form.html'

# add
def create_view(request):
    form = SparePartForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('rd:index')
    context = {
        'form': form,
    }
    return render(request, "rd/part_create.html", context)

# delete
class PartDeleteView(generic.DeleteView):
    model = SparePart
    template_name = 'rd/part_confirm_delete.html'
    success_url = '/rd/'

# API Views
from rest_framework import viewsets
from .serializers import SparePartSerializer

class SparePartViewSet(viewsets.ModelViewSet):
    queryset = SparePart.objects.all()
    serializer_class = SparePartSerializer

rd/templates/rd/index.html
{% load django_tables2 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rezervni deli</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" type="text/css" href="{% static 'rd/custom.css' %}">
</head>
<body>
    {% include 'rd/navbar.html' %}
    <h1>Seznam delov</h1>
    {% render_table table %}
</body>
</html>

rd/templates/rd/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'rd:index' %}">Rezervni Deli</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
            <a class="nav-link" href="{% url 'rd:index' %}">Seznam</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'rd:part_create' %}">Dodaj del</a>
            </li>
        </ul>
        </div>
    </div>
</nav>

rd/templates/rd/part_confirm_delete.html
{% load django_tables2 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rezervni deli</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" type="text/css" href="{% static 'rd/custom.css' %}">
</head>
<body>
    {% include 'rd/navbar.html' %}
    <h1>Sprememba podatkov za {{ sparepart.name }}</h1>
    <form method="POST">
        {% csrf_token %}
        <p> Ste prepričani, da želite izbrisati del "{{ sparepart.name }}"?</p>
        <button type="button" class="btn btn-secondary" onclick="location.href='{% url 'rd:detail' sparepart.id %}'">Prekliči</button>
        <button type="submit" class="btn btn-danger">Izbriši del</button>
    </form>
</body>
</html>

rd/templates/rd/part_create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rezervni deli</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" type="text/css" href="{% static 'rd/custom.css' %}">
</head>
<body> 
    {% include 'rd/navbar.html' %}
    <h1>Seznam delov</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary">Dodaj del</button>
</html>

rd/templates/rd/part_detail.html
{% load django_tables2 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rezervni deli</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" type="text/css" href="{% static 'rd/custom.css' %}">
</head>
<body>
    {% include 'rd/navbar.html' %}
    <h1>Podrobnosti dela: {{ sparepart.name }}</h1>
    <table class="table table-striped table-bordered w-auto">
        <tr>
            <th>ID</th>
            <td>{{ sparepart.id }}</td>
        </tr>
        <tr>
            <th>Naziv</th>
            <td>{{ sparepart.name }}</td>
        </tr>
        <tr>
            <th>Tip</th>
            <td>{{ sparepart.type }}</td>
        </tr>
        <tr>
            <th>Datum nabave</th>
            <td>{{ sparepart.dop }}</td>
        </tr>
        <tr>
            <th>Lastnik</th>
            <td>{{ sparepart.owner }}</td>
        </tr>
        <tr>
            <th>Lokacija</th>
            <td>{{ sparepart.location }}</td>
        </tr>
    </table>
    <button type="button" class="btn btn-primary" onclick="location.href='{% url 'rd:part_edit' sparepart.id %}'">Uredi del</button>
    <button type="button" class="btn btn-danger" onclick="location.href='{% url 'rd:part_delete' sparepart.id %}'">Izbriši del</button>
</body>
</html>

rd/templates/rd/part_form.html
{% load django_tables2 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rezervni deli</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" type="text/css" href="{% static 'rd/custom.css' %}">
</head>
<body>
    {% include 'rd/navbar.html' %}
    <h1>Sprememba podatkov za {{ sparepart.name }}</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary">Shrani spremembe</button>
</body>
</html>